# Generated by Django 4.2.24 on 2025-10-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_products', to='client.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_products', to='product.product')),
            ],
            options={
                'verbose_name': 'Client Product',
                'verbose_name_plural': 'Client Products',
                'ordering': ['-purchase_date'],
                'unique_together': {('client', 'product', 'purchase_date')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='products',
            field=models.ManyToManyField(related_name='clients', through='client.ClientProduct', to='product.product'),
        ),
    ]
