# Generated by Django 4.2.24 on 2025-10-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientproduct_client_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='products',
        ),
        migrations.DeleteModel(
            name='ClientProduct',
        ),
    ]
