# Generated by Django 4.2.24 on 2025-10-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_price',
        ),
    ]
