# Generated by Django 4.2.24 on 2025-10-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Product Detail')),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Price')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
