# Generated by Django 4.2.24 on 2025-10-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_client_products_delete_clientproduct'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
