# Generated by Django 4.2.24 on 2025-10-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_sold_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
